---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/jrichter1/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-HEAD
